spring.application.name=FirstSpringBoot


server.servlet.context-path=/firstspringboot
#server port change
server.port=8098

#JSP file configuration / view resolver
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

spring.datasource.url=jdbc:mysql://localhost:3306/jdbc_practice
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

image.path = R:/student_image

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-email-id
spring.mail.password=your-app-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true